export type TemplateFieldType = "text" | "number";

export type TemplateField = {
  key: string;
  label: string;
  placeholder: string;
  defaultValue: string;
  type?: TemplateFieldType;
  hint?: string;
};

export type GeneratedConfig = {
  config: string;
  rollback: string;
  validation: string[];
};

export type ConfigTemplate = {
  id: string;
  name: string;
  vendor: string;
  protocolArea: string;
  description: string;
  fields: TemplateField[];
  build: (values: Record<string, string>) => GeneratedConfig;
};

function v(values: Record<string, string>, key: string, fallback = ""): string {
  return (values[key] ?? "").trim() || fallback;
}

function vlanList(raw: string): string {
  return raw.replace(/\s+/g, "");
}

export const configTemplates: ConfigTemplate[] = [
  {
    id: "ios-base-hardening",
    name: "Base device hardening",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "Management",
    description: "Hostname, domain, SSHv2-only management, VTY hardening, and a login banner.",
    fields: [
      { key: "hostname", label: "Hostname", placeholder: "BR-SW-01", defaultValue: "BR-SW-01" },
      { key: "domain", label: "Domain name", placeholder: "corp.local", defaultValue: "corp.local" },
      { key: "mgmtAcl", label: "Management subnet (ACL permit)", placeholder: "10.120.10.0 0.0.0.255", defaultValue: "10.120.10.0 0.0.0.255", hint: "Wildcard mask format" },
      { key: "timeoutMin", label: "Exec timeout (minutes)", placeholder: "10", defaultValue: "10", type: "number" }
    ],
    build: (values) => {
      const hostname = v(values, "hostname", "DEVICE");
      const domain = v(values, "domain", "corp.local");
      const acl = v(values, "mgmtAcl", "10.0.0.0 0.255.255.255");
      const timeout = v(values, "timeoutMin", "10");
      return {
        config: `! Base hardening - generated by NGINEER
hostname ${hostname}
ip domain name ${domain}
crypto key generate rsa modulus 2048
ip ssh version 2
no ip http server
no ip http secure-server
service password-encryption
!
ip access-list standard MGMT-ACCESS
 permit ${acl}
 deny any log
!
line vty 0 15
 transport input ssh
 access-class MGMT-ACCESS in
 exec-timeout ${timeout} 0
 logging synchronous
!
banner motd ^ Authorized access only. Activity is monitored. ^`,
        rollback: `no banner motd
line vty 0 15
 no access-class MGMT-ACCESS in
 transport input ssh telnet
no ip access-list standard MGMT-ACCESS
no ip ssh version 2`,
        validation: [
          "Confirm an out-of-band path exists before applying the VTY access-class.",
          `Verify the management subnet ${acl} actually covers your admin workstations.`,
          "Test a new SSH session BEFORE closing the current one.",
          "RSA key generation requires hostname + domain to be set first (ordering matters)."
        ]
      };
    }
  },
  {
    id: "ios-access-port",
    name: "Layer 2 access port",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "Switching",
    description: "Access port with data + voice VLAN, PortFast, and BPDU Guard.",
    fields: [
      { key: "interface", label: "Interface", placeholder: "GigabitEthernet1/0/10", defaultValue: "GigabitEthernet1/0/10" },
      { key: "description", label: "Description", placeholder: "User workstation - Floor 2", defaultValue: "User workstation" },
      { key: "dataVlan", label: "Data VLAN", placeholder: "20", defaultValue: "20", type: "number" },
      { key: "voiceVlan", label: "Voice VLAN (blank = none)", placeholder: "120", defaultValue: "" }
    ],
    build: (values) => {
      const iface = v(values, "interface", "GigabitEthernet1/0/10");
      const data = v(values, "dataVlan", "20");
      const voice = v(values, "voiceVlan");
      return {
        config: `! L2 access port - generated by NGINEER
interface ${iface}
 description ${v(values, "description", "Access port")}
 switchport mode access
 switchport access vlan ${data}${voice ? `\n switchport voice vlan ${voice}` : ""}
 spanning-tree portfast
 spanning-tree bpduguard enable
 no shutdown`,
        rollback: `interface ${iface}
 no switchport access vlan
 ${voice ? "no switchport voice vlan\n " : ""}no spanning-tree portfast
 no spanning-tree bpduguard enable
 shutdown`,
        validation: [
          `Confirm VLAN ${data}${voice ? ` and voice VLAN ${voice}` : ""} exist on the switch (show vlan brief).`,
          "Never enable PortFast + BPDU Guard on a port facing another switch.",
          "Verify the upstream trunk carries the assigned VLAN(s)."
        ]
      };
    }
  },
  {
    id: "ios-trunk-port",
    name: "802.1Q trunk port",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "Switching",
    description: "Trunk with explicit allowed VLAN list and a non-default native VLAN.",
    fields: [
      { key: "interface", label: "Interface", placeholder: "GigabitEthernet1/0/48", defaultValue: "GigabitEthernet1/0/48" },
      { key: "description", label: "Description", placeholder: "Uplink to BR-CE-01 Gi0/0/1", defaultValue: "Uplink" },
      { key: "allowed", label: "Allowed VLANs", placeholder: "10,20,30,120", defaultValue: "10,20,30" },
      { key: "native", label: "Native VLAN", placeholder: "999", defaultValue: "999", type: "number" }
    ],
    build: (values) => {
      const iface = v(values, "interface", "GigabitEthernet1/0/48");
      const allowed = vlanList(v(values, "allowed", "10,20,30"));
      const native = v(values, "native", "999");
      return {
        config: `! 802.1Q trunk - generated by NGINEER
vlan ${native}
 name NATIVE-UNUSED
!
interface ${iface}
 description ${v(values, "description", "Trunk uplink")}
 switchport trunk encapsulation dot1q
 switchport mode trunk
 switchport trunk allowed vlan ${allowed}
 switchport trunk native vlan ${native}
 switchport nonegotiate
 no shutdown`,
        rollback: `interface ${iface}
 no switchport trunk allowed vlan
 no switchport trunk native vlan
 no switchport nonegotiate
 switchport mode dynamic auto`,
        validation: [
          "Allowed VLAN lists must match on BOTH ends of the trunk - mismatches blackhole traffic silently.",
          `Native VLAN ${native} must match the far end or you will see CDP native VLAN mismatch errors.`,
          "On platforms without 'switchport trunk encapsulation', omit that line (dot1q-only hardware).",
          "Pruning review: only carry VLANs this uplink actually needs."
        ]
      };
    }
  },
  {
    id: "ios-svi-gateway",
    name: "SVI gateway (inter-VLAN routing)",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "Switching",
    description: "VLAN definition plus routed SVI gateway interface.",
    fields: [
      { key: "vlanId", label: "VLAN ID", placeholder: "20", defaultValue: "20", type: "number" },
      { key: "vlanName", label: "VLAN name", placeholder: "Branch-Users", defaultValue: "Branch-Users" },
      { key: "ip", label: "Gateway IP", placeholder: "10.20.30.1", defaultValue: "10.20.30.1" },
      { key: "mask", label: "Subnet mask", placeholder: "255.255.255.0", defaultValue: "255.255.255.0" }
    ],
    build: (values) => {
      const vlan = v(values, "vlanId", "20");
      return {
        config: `! SVI gateway - generated by NGINEER
ip routing
!
vlan ${vlan}
 name ${v(values, "vlanName", `VLAN${vlan}`)}
!
interface Vlan${vlan}
 description Gateway for ${v(values, "vlanName", `VLAN${vlan}`)}
 ip address ${v(values, "ip", "10.0.0.1")} ${v(values, "mask", "255.255.255.0")}
 no shutdown`,
        rollback: `no interface Vlan${vlan}
no vlan ${vlan}`,
        validation: [
          "SVI comes up only when at least one access/trunk port in the VLAN is up (or use 'no autostate' where supported).",
          "Record this gateway in NGINEER IPAM before applying - duplicate gateway IPs cause immediate outages.",
          "'ip routing' enables L3 switching globally - confirm that is intended on this platform."
        ]
      };
    }
  },
  {
    id: "ios-ospf",
    name: "OSPF process",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "OSPF",
    description: "OSPF with router-id, passive-by-default, explicit network statements, and MD5-ready interface notes.",
    fields: [
      { key: "process", label: "Process ID", placeholder: "10", defaultValue: "10", type: "number" },
      { key: "routerId", label: "Router ID", placeholder: "10.255.0.1", defaultValue: "10.255.0.1" },
      { key: "network", label: "Network statement", placeholder: "10.20.0.0 0.0.255.255", defaultValue: "10.20.0.0 0.0.255.255", hint: "Wildcard mask" },
      { key: "area", label: "Area", placeholder: "0", defaultValue: "0", type: "number" },
      { key: "activeInterface", label: "Active (non-passive) interface", placeholder: "GigabitEthernet0/0/0", defaultValue: "GigabitEthernet0/0/0" }
    ],
    build: (values) => {
      const process = v(values, "process", "10");
      const active = v(values, "activeInterface", "GigabitEthernet0/0/0");
      return {
        config: `! OSPF - generated by NGINEER
router ospf ${process}
 router-id ${v(values, "routerId", "10.255.0.1")}
 passive-interface default
 no passive-interface ${active}
 network ${v(values, "network", "10.0.0.0 0.255.255.255")} area ${v(values, "area", "0")}
 auto-cost reference-bandwidth 100000
!
! Optional interface authentication (recommended):
! interface ${active}
!  ip ospf message-digest-key 1 md5 <key>
!  ip ospf authentication message-digest`,
        rollback: `no router ospf ${process}`,
        validation: [
          "Router-id must be unique in the OSPF domain; prefer a loopback address.",
          "passive-interface default means adjacency forms ONLY on listed no-passive interfaces - verify the right ones.",
          "reference-bandwidth must match on all routers or costs become inconsistent.",
          "Check adjacency after apply: show ip ospf neighbor."
        ]
      };
    }
  },
  {
    id: "ios-eigrp",
    name: "EIGRP (named mode)",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "EIGRP",
    description: "Named-mode EIGRP with AS, router-id, network statement, and passive default.",
    fields: [
      { key: "name", label: "Instance name", placeholder: "CORP", defaultValue: "CORP" },
      { key: "asn", label: "AS number", placeholder: "100", defaultValue: "100", type: "number" },
      { key: "routerId", label: "Router ID", placeholder: "10.255.0.1", defaultValue: "10.255.0.1" },
      { key: "network", label: "Network statement", placeholder: "10.20.0.0 0.0.255.255", defaultValue: "10.20.0.0 0.0.255.255" },
      { key: "activeInterface", label: "Active interface", placeholder: "GigabitEthernet0/0/0", defaultValue: "GigabitEthernet0/0/0" }
    ],
    build: (values) => {
      const name = v(values, "name", "CORP");
      const asn = v(values, "asn", "100");
      const active = v(values, "activeInterface", "GigabitEthernet0/0/0");
      return {
        config: `! EIGRP named mode - generated by NGINEER
router eigrp ${name}
 address-family ipv4 unicast autonomous-system ${asn}
  eigrp router-id ${v(values, "routerId", "10.255.0.1")}
  network ${v(values, "network", "10.0.0.0 0.255.255.255")}
  af-interface default
   passive-interface
  exit-af-interface
  af-interface ${active}
   no passive-interface
  exit-af-interface
 exit-address-family`,
        rollback: `no router eigrp ${name}`,
        validation: [
          "AS numbers must match between neighbors or no adjacency forms.",
          "K-values must match between neighbors (defaults are fine unless someone tuned them).",
          "Verify with: show ip eigrp neighbors / show ip eigrp topology."
        ]
      };
    }
  },
  {
    id: "ios-bgp",
    name: "BGP peering",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "BGP",
    description: "eBGP/iBGP neighbor with router-id, network advertisement, and soft-reconfiguration.",
    fields: [
      { key: "localAs", label: "Local AS", placeholder: "65010", defaultValue: "65010", type: "number" },
      { key: "routerId", label: "Router ID", placeholder: "10.255.0.1", defaultValue: "10.255.0.1" },
      { key: "neighborIp", label: "Neighbor IP", placeholder: "203.0.113.1", defaultValue: "203.0.113.1" },
      { key: "remoteAs", label: "Neighbor remote AS", placeholder: "65000", defaultValue: "65000", type: "number" },
      { key: "advertise", label: "Network to advertise", placeholder: "10.20.0.0", defaultValue: "10.20.0.0" },
      { key: "advertiseMask", label: "Network mask", placeholder: "255.255.0.0", defaultValue: "255.255.0.0" }
    ],
    build: (values) => {
      const localAs = v(values, "localAs", "65010");
      const neighbor = v(values, "neighborIp", "203.0.113.1");
      return {
        config: `! BGP - generated by NGINEER
router bgp ${localAs}
 bgp router-id ${v(values, "routerId", "10.255.0.1")}
 bgp log-neighbor-changes
 neighbor ${neighbor} remote-as ${v(values, "remoteAs", "65000")}
 neighbor ${neighbor} description NGINEER-generated peer
 !
 address-family ipv4 unicast
  neighbor ${neighbor} activate
  neighbor ${neighbor} soft-reconfiguration inbound
  network ${v(values, "advertise", "10.20.0.0")} mask ${v(values, "advertiseMask", "255.255.0.0")}
 exit-address-family`,
        rollback: `router bgp ${localAs}
 no neighbor ${neighbor}`,
        validation: [
          "The advertised network must exist in the routing table exactly (network+mask) or it will not be announced.",
          "eBGP peers should be directly connected or configured with ebgp-multihop.",
          "Apply inbound/outbound prefix filters before peering with any external AS - never run an open eBGP session.",
          "Verify with: show bgp ipv4 unicast summary."
        ]
      };
    }
  },
  {
    id: "ios-stp",
    name: "Spanning tree (Rapid-PVST+ root)",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "STP",
    description: "Rapid-PVST+ mode, deterministic root placement for selected VLANs, and global edge protections.",
    fields: [
      { key: "rootVlans", label: "VLANs to root here", placeholder: "10,20,30", defaultValue: "10,20,30" },
      { key: "secondaryVlans", label: "VLANs to be secondary root (blank = none)", placeholder: "40,50", defaultValue: "" }
    ],
    build: (values) => {
      const primary = vlanList(v(values, "rootVlans", "1"));
      const secondary = vlanList(v(values, "secondaryVlans"));
      return {
        config: `! Spanning tree - generated by NGINEER
spanning-tree mode rapid-pvst
spanning-tree extend system-id
spanning-tree vlan ${primary} root primary${secondary ? `\nspanning-tree vlan ${secondary} root secondary` : ""}
!
spanning-tree portfast bpduguard default
errdisable recovery cause bpduguard
errdisable recovery interval 300`,
        rollback: `no spanning-tree vlan ${primary} root primary${secondary ? `\nno spanning-tree vlan ${secondary} root secondary` : ""}
no spanning-tree portfast bpduguard default
no errdisable recovery cause bpduguard`,
        validation: [
          "Root primary lowers priority to win election - confirm THIS switch should be root for those VLANs.",
          "Changing STP mode is briefly disruptive; schedule a window.",
          "bpduguard default applies to PortFast ports only - trunks are unaffected.",
          "Verify with: show spanning-tree root / show spanning-tree summary."
        ]
      };
    }
  },
  {
    id: "ios-mpls-ldp",
    name: "MPLS LDP core enablement",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "MPLS",
    description: "Enable label switching with LDP on core-facing interfaces with an explicit LDP router-id.",
    fields: [
      { key: "loopback", label: "LDP router-id interface", placeholder: "Loopback0", defaultValue: "Loopback0" },
      { key: "coreInterfaceA", label: "Core interface 1", placeholder: "GigabitEthernet0/0/0", defaultValue: "GigabitEthernet0/0/0" },
      { key: "coreInterfaceB", label: "Core interface 2 (blank = none)", placeholder: "TenGigabitEthernet0/0/1", defaultValue: "" }
    ],
    build: (values) => {
      const loopback = v(values, "loopback", "Loopback0");
      const a = v(values, "coreInterfaceA", "GigabitEthernet0/0/0");
      const b = v(values, "coreInterfaceB");
      return {
        config: `! MPLS LDP - generated by NGINEER
mpls ip
mpls label protocol ldp
mpls ldp router-id ${loopback} force
!
interface ${a}
 mpls ip${b ? `\n!\ninterface ${b}\n mpls ip` : ""}`,
        rollback: `interface ${a}
 no mpls ip${b ? `\n!\ninterface ${b}\n no mpls ip` : ""}
no mpls ldp router-id ${loopback} force
no mpls ip`,
        validation: [
          `${loopback} must be reachable via the IGP before LDP sessions form - LDP rides on the IGP.`,
          "Both ends of each core link need 'mpls ip' or labels will not be exchanged.",
          "MTU: label stack adds 4 bytes per label - verify core MTU accommodates it.",
          "Verify with: show mpls ldp neighbor / show mpls forwarding-table."
        ]
      };
    }
  },
  {
    id: "ios-static-route",
    name: "Static / default route",
    vendor: "Cisco IOS/IOS-XE",
    protocolArea: "Routing",
    description: "Static route with optional administrative distance for floating backup paths.",
    fields: [
      { key: "prefix", label: "Destination network", placeholder: "0.0.0.0", defaultValue: "0.0.0.0" },
      { key: "mask", label: "Mask", placeholder: "0.0.0.0", defaultValue: "0.0.0.0" },
      { key: "nextHop", label: "Next hop", placeholder: "203.0.113.1", defaultValue: "203.0.113.1" },
      { key: "distance", label: "Admin distance (blank = 1)", placeholder: "250", defaultValue: "" }
    ],
    build: (values) => {
      const prefix = v(values, "prefix", "0.0.0.0");
      const mask = v(values, "mask", "0.0.0.0");
      const nextHop = v(values, "nextHop", "203.0.113.1");
      const distance = v(values, "distance");
      const line = `ip route ${prefix} ${mask} ${nextHop}${distance ? ` ${distance}` : ""}`;
      return {
        config: `! Static route - generated by NGINEER\n${line}`,
        rollback: `no ${line}`,
        validation: [
          "Next hop must be reachable on a connected segment (or use an exit interface + next hop).",
          distance ? `Distance ${distance} makes this a floating route - it activates only when the primary disappears.` : "Default distance 1 beats all dynamic protocols - confirm that is intended.",
          "Check for route shadowing against existing statics and dynamic routes."
        ]
      };
    }
  }
];
